=== Madioter/hbatis/src/main/java/com/madiot/hbatis/builder/xml/hbatis-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2017 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use this file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | put* | delete* | select* )+>
        <!ATTLIST mapper
                namespace CDATA #IMPLIED
                >

        <!ELEMENT cache-ref EMPTY>
        <!ATTLIST cache-ref
                namespace CDATA #REQUIRED
                >

        <!ELEMENT cache (property*)>
        <!ATTLIST cache
                type CDATA #IMPLIED
                eviction CDATA #IMPLIED
                flushInterval CDATA #IMPLIED
                size CDATA #IMPLIED
                readOnly CDATA #IMPLIED
                blocking CDATA #IMPLIED
                >

        <!ELEMENT parameterMap (parameter+)?>
        <!ATTLIST parameterMap
                id CDATA #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT parameter EMPTY>
        <!ATTLIST parameter
                property CDATA #REQUIRED
                javaType CDATA #IMPLIED
                mode (IN | OUT | INOUT) #IMPLIED
                resultMap CDATA #IMPLIED
                scale CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT resultMap (constructor?,rowkey*,result*,association*,collection*, discriminator?)>
        <!ATTLIST resultMap
                id CDATA #REQUIRED
                type CDATA #REQUIRED
                extends CDATA #IMPLIED
                autoMapping (true|false) #IMPLIED
                >

        <!ELEMENT constructor (idArg*,arg*)>

        <!ELEMENT rowkey EMPTY>
        <!ATTLIST rowkey
                property CDATA #IMPLIED
                javaType CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT result EMPTY>
        <!ATTLIST result
                property CDATA #IMPLIED
                javaType CDATA #IMPLIED
                qualifier CDATA #IMPLIED
                family CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT idArg EMPTY>
        <!ATTLIST idArg
                javaType CDATA #IMPLIED
                column CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                name CDATA #IMPLIED
                >

        <!ELEMENT arg EMPTY>
        <!ATTLIST arg
                javaType CDATA #IMPLIED
                column CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                name CDATA #IMPLIED
                >

        <!ELEMENT collection (constructor?,rowkey*,result*,association*,collection*, discriminator?)>
        <!ATTLIST collection
                property CDATA #REQUIRED
                column CDATA #IMPLIED
                javaType CDATA #IMPLIED
                ofType CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                notNullColumn CDATA #IMPLIED
                columnPrefix CDATA #IMPLIED
                resultSet CDATA #IMPLIED
                foreignColumn CDATA #IMPLIED
                autoMapping (true|false) #IMPLIED
                fetchType (lazy|eager) #IMPLIED
                >

        <!ELEMENT association (constructor?,rowkey*,result*,association*,collection*, discriminator?)>
        <!ATTLIST association
                property CDATA #REQUIRED
                column CDATA #IMPLIED
                javaType CDATA #IMPLIED
                select CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                typeHandler CDATA #IMPLIED
                notNullColumn CDATA #IMPLIED
                columnPrefix CDATA #IMPLIED
                resultSet CDATA #IMPLIED
                foreignColumn CDATA #IMPLIED
                autoMapping (true|false) #IMPLIED
                fetchType (lazy|eager) #IMPLIED
                >

        <!ELEMENT discriminator (case+)>
        <!ATTLIST discriminator
                column CDATA #IMPLIED
                javaType CDATA #REQUIRED
                typeHandler CDATA #IMPLIED
                >

        <!ELEMENT case (constructor?,rowkey*,result*,association*,collection*, discriminator?)>
        <!ATTLIST case
                value CDATA #REQUIRED
                resultMap CDATA #IMPLIED
                resultType CDATA #IMPLIED
                >

        <!ELEMENT property EMPTY>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT typeAlias EMPTY>
        <!ATTLIST typeAlias
                alias CDATA #REQUIRED
                type CDATA #REQUIRED
                >

        <!ELEMENT select (#PCDATA | filters | filter | selectKey | column | where | set | foreach | choose | if | bind)*>
        <!ATTLIST select
                id CDATA #REQUIRED
                tableName CDATA #REQUIRED
                caching CDATA #IMPLIED
                batch CDATA #IMPLIED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                resultMap CDATA #IMPLIED
                resultType CDATA #IMPLIED
                resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
                statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
                fetchSize CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
                useCache (true|false) #IMPLIED
                databaseId CDATA #IMPLIED
                lang CDATA #IMPLIED
                resultOrdered (true|false) #IMPLIED
                resultSets CDATA #IMPLIED
                >

        <!ELEMENT filters (#PCDATA | filter | if | foreach)*>
        <!ATTLIST filters
                operator CDATA #IMPLIED
                >

        <!ELEMENT filter (#PCDATA | comparator | filter | param | if | foreach)*>
        <!ATTLIST filter
                type CDATA #REQUIRED
                compareOp CDATA #IMPLIED
                family CDATA #IMPLIED
                qualifier CDATA #IMPLIED
                >

        <!ELEMENT param EMPTY>
        <!ATTLIST param
                key CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT comparator (#PCDATA | if | foreach)*>
        <!ATTLIST comparator
                type CDATA #REQUIRED
                value CDATA #IMPLIED
                param CDATA #IMPLIED
                >


        <!ELEMENT versions EMPTY>
        <!ATTLIST versions
                timestamp CDATA #IMPLIED
                minstamp CDATA #IMPLIED
                maxstamp CDATA #IMPLIED
                maxVersions CDATA #IMPLIED
                >

        <!ELEMENT limit EMPTY>
        <!ATTLIST limit
                startRow CDATA #IMPLIED
                stopRow CDATA #IMPLIED
                >

        <!ELEMENT put (#PCDATA | selectKey | trim | set | foreach | if | bind)*>
        <!ATTLIST put
                id CDATA #REQUIRED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
                tableName CDATA #REQUIRED
                >

        <!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST selectKey
                value CDATA #REQUIRED
                timestamp CDATA #IMPLIED
                >

        <!ELEMENT delete (#PCDATA | selectKey | foreach | if | bind | column)*>
        <!ATTLIST delete
                id CDATA #REQUIRED
                tableName CDATA #REQUIRED
                parameterMap CDATA #IMPLIED
                parameterType CDATA #IMPLIED
                timeout CDATA #IMPLIED
                flushCache (true|false) #IMPLIED
                >

        <!-- Dynamic -->

        <!ELEMENT include (property+)?>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >

        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST sql
                id CDATA #REQUIRED
                lang CDATA #IMPLIED
                databaseId CDATA #IMPLIED
                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                prefixOverrides CDATA #IMPLIED
                suffix CDATA #IMPLIED
                suffixOverrides CDATA #IMPLIED
                >
        <!ELEMENT where (#PCDATA | versions | limit | include | trim | where | set | foreach | choose | if | bind)*>
        <!ELEMENT set (#PCDATA | column | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT column EMPTY>
        <!ATTLIST column
                family CDATA #REQUIRED
                qualifier CDATA #IMPLIED
                value CDATA #IMPLIED
                timestamp CDATA #IMPLIED
                type CDATA #IMPLIED
                >

        <!ELEMENT foreach (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when* , otherwise?)>
        <!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >
        <!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== Madioter/hbatis/src/main/java/test/mapper/UserMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "" "/com/madiot/builder/xml/hbatis-mapper.dtd" >
<mapper namespace="test.mapper.UserMapper">
    <resultMap id="BaseResultMap" type="test.domain.User">
        <rowkey property="userName"/>
        <result family="base-info" qualifier="user_pass" property="userPass" javaType="test.domain.UserPass"/>
        <result family="base-info" qualifier="user_age" property="age"/>
    </resultMap>

    <!-- 单条新增 -->
    <put id="put" parameterType="test.domain.User" tableName="t_user">
        <selectKey value="#{userName}"/>
        <set>
            <column family="base-info" qualifier="user_pass" value="#{userPass,javaType=test.domain.UserPass}"/>
            <column family="base-info" qualifier="user_age" value="#{age}"/>
        </set>
    </put>

    <!-- 批量新增 -->
    <put id="putBatch" parameterType="java.util.List" tableName="t_user">
        <foreach collection="list" item="item" index="index">
            <selectKey value="#{item.userName}"/>
            <set>
                <column family="base-info" qualifier="user_pass"
                        value="#{item.userPass,javaType=test.domain.UserPass}"/>
                <column family="base-info" qualifier="user_age" value="#{item.age}"/>
            </set>
        </foreach>
    </put>

    <delete id="delete" tableName="t_user">
        <selectKey value="#{rowkey}"/>
        <column family="base-info" timestamp="#{version}" type="before"/>
    </delete>

    <delete id="deleteBatch" tableName="t_user">
        <foreach collection="list" item="item" index="index">
            <selectKey value="#{item}"/>
        </foreach>
    </delete>

    <select id="getById" tableName="t_user" resultMap="BaseResultMap">
        <selectKey value="#{rowkey}"/>
        <column family="base-info"/>
        <where>
            <versions maxVersions="3"/>
        </where>
    </select>

    <select id="selectBaseInfo" tableName="t_user" resultMap="BaseResultMap" caching="10" batch="2">
        <column family="base-info"/>
        <filters operator="MUST_PASS_ONE">
            <filter type="rowFilter" compareOp="LESS_OR_EQUAL">
                <comparator type="binary" value="#{value, javaType=java.lang.String}"/>
            </filter>
            <filter type="columnPaginationFilter">
                <param key="limit" value="1"/>
                <param key="offset" value="1"/>
            </filter>
        </filters>
        <where>
            <limit startRow="aaa"/>
        </where>
    </select>
</mapper>
